### ISSUE TITLE
Feature Request: read-only pre-0.10 BackupStorageLocation

### ISSUE THREAD

**Issue by bryanlarsen** [heptio/velero#1130]
I'm trying to transfer from an older cluster to a new cluster.   During the transition, both clusters need to be up.

The old cluster runs ark 0.8.1, the new one 0.10.0.   I figured I'd just take advantage of your new support for multiple locations, and add both the old and new buckets to the new ark setup.   However, when I do that, I get the error:

`An error occurred: some backup storage locations are invalid: backup store for location "aws-old" is invalid (if upgrading from a pre-v0.10 version of Ark, please refer to https://heptio.github.io/ark/v0.10.0/storage-layout-reorg-v0.10 for instructions): Backup store contains 570 invalid top-level directories:`

I can't transition the old bucket because the old cluster is still using it.   I don't want to upgrade the old cluster because the whole point is to get rid of it; also the cluster is somewhat fragile/broken so I want to touch as little as possible.

It'd be nice to have a way to use a pre-0.10 BackupStorageLocation.   This can & should be read-only.

**Environment:**

- Ark version (use `ark version`): 0.8.1 and 0.10.0
- Kubernetes version (use `kubectl version`): v1.11.2
- Kubernetes version: v1.9.7 & v1.11.4-gke.12
- Cloud provider or hardware configuration: metal/kubespray & GKE
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.1

**Comment by skriss** [comment]
hi @bryanlarsen - my recommendation would be to do a full copy of your v0.8.1 bucket into a new bucket, and then to use the script [here](https://github.com/heptio/ark/blob/master/docs/storage-layout-reorg-v0.10.md#rclone-based-script) to upgrade *the new bucket* to be v0.10-compatible, which you can then add as a backup storage location to your v0.10 install.  So the steps would be something like:

1. copy the full contents of your v0.8.1 bucket to a new bucket (I'll call it `migration-bucket`). We won't touch the v0.8.1 source bucket in any of the subsequent steps
2. run our [migration script](https://github.com/heptio/ark/blob/master/docs/storage-layout-reorg-v0.10.md#rclone-based-script) against `migration-bucket` to upgrade it to be v0.10-compatible (note that the script will create a third temporary bucket in order to perform the migration)
3. configure a `BackupStorageLocation` that points to `migration-bucket`.
4. if appropriate, put the v0.10 ark instance into restore-only mode, as documented [here in step 7b.](https://github.com/heptio/ark/blob/master/docs/upgrading-to-v0.10.md#step-by-step-upgrade-instructions)

Hope this helps - let me know if you have any questions!

**Comment by bryanlarsen** [comment]
The procedure you're describing is a one time procedure, I need something ongoing.  For a ~ two week period, both the old & new clusters will be writing to their respective buckets.

It appears that I can just copy backup directories from the old bucket into the new bucket, though.   I lose some metadata (the created timestamp on the copied backup is 0001-01-01 00:00:00 +0000 UTC for some reason), but it still worked for a restore.

**Comment by bryanlarsen** [comment]
Perhaps I spoke too soon.    I was able to do this for one backup, but when I tried it for another, it's not showing up in `ark backup get`.

**Comment by bryanlarsen** [comment]
to get it to pick up the new directory I deleted metadata/revision and restarted the pod.

**Comment by skriss** [comment]
Ah, I see. Yes - if you manually copy backups into the v0.10 bucket, you either need to delete the `metadata/revision` file, or wait up to an hour for those backups to appear. Ark's using the `revision` file to determine if the bucket contents have changed, as it doesn't expect anyone else to be modifying the contents.

Perhaps you could set up a periodic s3 sync job to copy backups from the v0.8.1 bucket into the v0.10 bucket?

**Comment by skriss** [comment]
I liked the idea here but as we're approaching v1.0 this is no longer something we're going to prioritize. Closing as "Won't Fix".
