### ISSUE TITLE
Improve handling of PersistentVolumes with Retain reclaim policy

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#1151]
PersistentVolumes can have a reclaim policy of either Delete or Retain.

When a PVC is deleted, if the PV's reclaim policy is Delete, the underlying storage disk is deleted and the PV is deleted.

When a PVC is deleted, if the PV's reclaim policy is Retain, the underlying storage disk is preserved, and the PV remains.

Ark works quite well with Delete:
- if we have a native snapshot, we create a new storage disk from the snapshot, then associate it with the PV
- if we have a restic snapshot, we don't restore the PV, and instead only restore the PVC, which results in a new PV being created, and then we restic restore into it

Ark doesn't work as well with Retain, depending on your restore scenario:
- if you've "lost" your cluster or a portion of it, but you still have the underlying storage disk, and you're restoring into the same project/region/zone (if in the cloud), then we restore the PV and keep its association to the original underlying storage disk, so you get back to where you were pre-disaster
- if you're trying to restore into a new cluster and you don't want to reuse the underlying storage disk, restoring the PV and preserving the association to the underlying storage disk is a problem

We should try to figure out how to handle the 80-90% case as well as possible. Maybe we need a new flag when creating the restore that indicates how to handle Retain PVs - to either keep the current behavior of preserving the association to the underlying disk, or to wipe the association and restore from a snapshot (if we have one) or create a new disk (assuming we have a restic snapshot).

Discuss!

**Comment by apoplawski** [comment]
Hi, I brought up the issue on Slack. My use case is that with Ark + Restic I try to **clone** whole cluster to another one - both are on Azure. Most of my PVs reclaim policy is _retain_. The Cluster1 is up and running all the time, the PVs on Cluster1 are bound and I'd like all of backed up volumes to be provisioned anew.
But during restore onto Cluster2 process hangs, Ark tries to reuse the PVs (instead of provisioning new ones) and fails due to access error or inability to mount the volume that's already mounted on Cluster1.

The easiest solution IMO probably would be adding new flag to ark-cli, letting the user decide if he wants to have all the PVs dynamically provisioned.
 
Another idea: maybe seeing that PV status is _bound_, checking its reclaim policy and knowing that we have a restic snapshot might indicate that we need to provision a new volume?

**Comment by skriss** [comment]
Having walked through another occurrence of this today with a user, I feel like it's always expected behavior that if you back up a PV using restic, then on restore, it gets restored from restic.  That would imply that *even if* the reclaim policy is Retain, on restore we should re-provision an empty volume and use restic to restore its contents.  This is consistent with how we treat Retain PVs that have snapshots - if there's a snapshot, then we restore the PV from snapshot.

If that's the case, then rather than adding another CLI/API toggle, I'd prefer to just fix the bug for the case where a Retain PV has a restic backup.  This would be difficult to implement in our current restore code, though, because there's no easy way to determine if there's a restic backup of a PV (restic operates at the pod volume level).  

However - if we could track in our `volumesnapshots.json` file when a PV has been backed up using restic (currently this only has entries for PVs that were snapshotted), then it would become easy during a restore to know whether a PV had a restic backup or not.  And, it looks like it should be easy to add that info to the file at backup time.

What do you all think? Is this a crazy idea? Would appreciate your input @ncdc if you have time!

**Comment by uschtwill** [comment]
So it ought to be "Retain" in the title, instead of "Delete"?

**Comment by skriss** [comment]
@nrb @carlisia would appreciate your input on https://github.com/heptio/velero/issues/1151#issuecomment-463849604. We can discuss in person once you've had a chance to look.

**Comment by nrb** [comment]
> However - if we could track in our volumesnapshots.json file when a PV has been backed up using restic (currently this only has entries for PVs that were snapshotted), then it would become easy during a restore to know whether a PV had a restic backup or not. And, it looks like it should be easy to add that info to the file at backup time.

I like this idea, partially because by merging these we could report restic volumes in the PV section of our describe commands. Right now, having 2 sections depending on how your PV was backed up (native snapshot vs restic) is a little confusing.

I also agree with matching the restore logic regardless of whether a PV is coming from a native snapshot or restic. Again, having different behaviors between native and restic is confusing and the closer we can get them, the easier the whole process is to understand.

**Comment by carlisia** [comment]
+1 for what @nrb said.

**Comment by skriss** [comment]
@nrb @carlisia I assigned the P1 label to this back in March, but I don't actually think it's must-have for v1.0 as it's a non-breaking change and a specific scenario - are you all cool with me changing it to a P2?

**Comment by carlisia** [comment]
> I like this idea, partially because by merging these we could report restic volumes in the PV section of our describe commands. Right now, having 2 sections depending on how your PV was backed up (native snapshot vs restic) is a little confusing.

Just wanted to connect the idea above ^ with this new issue: https://github.com/heptio/velero/issues/1476

**Comment by skriss** [comment]
ref. https://github.com/heptio/velero/pull/1538
