### ISSUE TITLE
Links to version-specific pages in headers of master docs at heptio.github.io/velero/master are broken

### ISSUE THREAD

**Issue by nzoueidi** [heptio/velero#1216]
**What steps did you take and what happened:**
The latest version in https://heptio.github.io/velero/master/versions.html points to `v0.10.0versions.html` which is not found.

**What did you expect to happen:**
When I click on the link, it takes me to the latest version.

**Comment by skriss** [comment]
More generally - the `master` version of our docs site at https://heptio.github.com/velero/master has a warning at the top of each page:

"This is the documentation for the latest development version of Velero. Both code and docs may be unstable, and these docs are not guaranteed to be up to date or correct. See the *latest version*."

Where "latest version" is a link to the latest version-specific instance of that page.  These links are broken on all pages except the landing page -- looks like there's a missing `/` in the URL.  E.g. `https://heptio.github.io/velero/v0.10.0versions.html` instead of `https://heptio.github.io/velero/v0.10.0/versions.html`.

**Comment by carlisia** [comment]
I'll test this.

**Comment by skriss** [comment]
Closed by #1239
