### ISSUE TITLE
Archiving data on S3

### ISSUE THREAD

**Issue by hibbert** [heptio/velero#1276]
**Anything else you would like to add:**

I'm looking for some advice on archiving data as it doesn't look like this is built into the tool. I'm therefore looking into setting up Object lifecycle policies on the bucket just wandering if there is any advice on this? Looking to run the backup daily and will be backing up restic data with the tool too.

**Environment:**

AWS, S3, Restic

**Comment by skriss** [comment]
@hibbert I don't have much input to offer here - never tried setting this up.

**Comment by hibbert** [comment]
I'm not looking for how to use object lifecycle policies with an S3 bucket, I'm asking whether this could have any adverse affects with data backed up by velero + restic as I'm not sure if pruning is part of the tool, or having a hard time finding out for sure.

The kubernetes resources (without volumes), isn't going to be very big I guess but, over time it would build up, when you run "velero get backups" it has an EXPIRES column, is it removing stuff itself including doing a restic prune?

I think potentially it is, it's just not that clear

velero in general - https://github.com/heptio/velero/blob/1675943f44dfec16f369d631046e52f6f252283c/docs/about.md

restic I guess is presumably running a prune when the ttl of the main backup is reached (I guess the default must be 30 days) - https://github.com/heptio/velero/blob/78bf8fb868410a10db45f5fd5779877c52fc46fa/pkg/restic/repository_manager.go#L56

I guess I'm just looking for some clarity as to whether it does do expiry/pruning of data? How I can find out what the limits are? Whether the expiry you see when you run "velero get backups" is also tied into a "restic prune" command?

**Comment by skriss** [comment]
Ah. so when a Velero backup expires according to the TTL, the non-restic data gets deleted from object storage, along with the backup CRD. If there are restic snapshots associated with that backup, `restic forget` will be run for them. This doesn't actually remove their underlying data - it basically just removes the metadata from the restic repo about the snapshot.  Separately, every 24h (by default) we run "maintenance" on each restic repo, which includes running `restic prune` -- which will remove any blocks of data that are no longer needed (i.e. due to a snapshot having been forgotten).  The 24h interval is configurable via the `resticrepository` CRD's `.spec.maintenanceFrequency` field.

See https://restic.readthedocs.io/en/latest/060_forget.html for some more detail on forget vs. prune.

**Comment by skriss** [comment]
Did this answer your question @hibbert? Anything else needed on this issue?

**Comment by skriss** [comment]
Closing issue, feel free to reopen as needed.
