### ISSUE TITLE
Clean up non-restartable plugins

### ISSUE THREAD

**Issue by carlisia** [heptio/velero#1292]
Verify if any of the plugin client code restartable and if so, delete.

**Comment by nrb** [comment]
I changed the title - my idea was to remove any of the old plugin code that wasn't restartable, and move all the restartable code to use those names.

The renaming part may be unnecessary or undesirable, but I think at least removing the older, non-restartable plugin code would be a good idea by 1.0 in order to reduce confusion.

**Comment by skriss** [comment]
I don't think there's anything in there that's not being used - @carlisia @nrb did you have something specific in mind?

**Comment by carlisia** [comment]
@nrb mentioned it and I left it to be investigated as part of this issue. Didn't comb thru it.

**Comment by skriss** [comment]
@nrb @carlisia let's sort out if there's anything to do here (I don't believe there is) and close this issue out one way or another.

**Comment by nrb** [comment]
There's nothing to do here; I was mistaken about what some of the files I saw were doing. Plus, the refactoring work already done has removed them.
