### ISSUE TITLE
Provide a way to change full sync period

### ISSUE THREAD

**Issue by nrb** [heptio/velero#1343]
**Describe the solution you'd like**
When using Velero as a component in a larger backup system, we were looking for a way to sync the object store data more often than once an hour. This was done because backups using Velero's format were being written to the bucket out-of-band, but we wanted Velero to sync them into the cluster shortly after upload.

A hack around this was to delete the  `metadata/revision` file. The follow on effect there was that the entire bucket was scanned once a minute, and will be until the Velero server either performs or deletes a backup. This approach is also fragile, as we intend to do verification checks with #1072.

Ideally, we would be able to issue a command that does the sync on demand, as well as with the schedule.

**Comment by skriss** [comment]
Rather than delete the revision file, you can update the contents with a new GUID, which should avoid the drawback you describe.

We should think about this a little bit - do we want to accommodate external modifications to the object storage bucket? That potentially opens up a number of other issues, so I'd want to carefully consider before going ahead with implementation.

**Comment by nrb** [comment]
Another way to accomplish this would be to edit the `BackupStorageLocation.Status` to remove the `LastSyncedRevision` and `LastSyncedTime`. This way, the controller has no record of a sync, and will trigger a full sync in ~60 seconds.

**Comment by skriss** [comment]
We could potentially also stop using the `revision` file while still keeping the # of cloud provider API calls reasonable.  The idea with the `revision` file was that it would be easy to know when *Velero* has made changes to the contents of the object storage bucket; however, it doesn't work well if the bucket contents are being changed outside Velero, *or* CRDs are manually being deleted.  

Instead of using `revision`, we could run the `backupStore.ListBackups`  method once per sync interval (e.g. 1m), which is only a single API call to list prefixes (i.e. backup names) from object storage. We could then compare that set of backup names to what's in-cluster as CRDs, and sync (create/delete) as necessary.

I think this is still more efficient cloud-provider-API-call-wise than the sync used to be, while still responding to changes either in-cluster or in-bucket in a timely way, and handles more scenarios.

**Comment by skriss** [comment]
Thinking about this more, I can't really see any drawbacks to https://github.com/heptio/velero/issues/1343#issuecomment-519605161. It simplifies the sync process, it allows users to more directly control how often the "full sync" happens, and it means Velero reacts more quickly to behind-the-scenes changes to BSL bucket contents.

Once per sync interval (which is already user-configurable with a server flag), we'll issue a single object store API call per BSL to list backup names from the BSL bucket. Then, we'll check by name which ones don't exist already in the cluster, and sync those in. In the normal case (where there are no backups to sync in), we issue only one cloud API call per BSL per sync interval, which is the same as now with the `revision` file.

**Comment by carlisia** [comment]
No matter what, I really like this.

But also, and I could be wrong, I think it would avoid repeatedly getting the error "Unable to get backup store's revision file" for the first backup for a BSL when the backup gets stuck in "InProgress".

**Comment by skriss** [comment]
It would avoid that log message, yeah.
