### ISSUE TITLE
Infinite loop when following the instructions

### ISSUE THREAD

**Issue by cbluth** [heptio/velero#1382]
![1555565061503](https://user-images.githubusercontent.com/6709636/56338624-02747800-61ab-11e9-84a5-d649b0d27dc2.png)
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Please see the attached screenshot. The documentation has an infinite loop.

**What did you expect to happen:**
I was looking for the install documentation.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
ok, thanks @cbluth.

**Comment by skriss** [comment]
The problem here is there's no way to link to the "latest" version of a specific page on the docs site -- e.g. having `https://heptio.github.io/velero/latest/install-overview` redirect to `https://heptio.github.io/velero/v0.11.0/install-overview`. So we're just linking to the main page - which yes, if you're viewing this from the docs site, is just a link to itself, but if you're viewing the README in the github repo, it brings you to the docs site. Not sure there's much to be done here atm. @jonasrosland with the docs site updates, will there be any easy way to link to the "latest" version tag of the docs?
