### ISSUE TITLE
Please add a method to list plugins from the velero CLI

### ISSUE THREAD

**Issue by cormachogan** [heptio/velero#1475]
**Describe the solution you'd like**
At the moment, the velero CLI only provides a way to add or remove plugins. It does not provide a way to list plugins. This would be a nice feature to include in the velero CLI, esepcially when trying to determine which version of a plugin you may have previously installed.

**Environment:**

- Velero version: (use `v0.11`):
- Kubernetes version: (use `1.14.1`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration: vSphere VCP
- OS (e.g. from `/etc/os-release`): Ubuntu 17.10

**Comment by carlisia** [comment]
To double check: going the `ServerStatusRequest`, the idea is to output the list via the `velero plugin list` cmd still? Or together with the status?

**Comment by skriss** [comment]
So right now, `velero version` is the only CLI command that creates/displays a `ServerStatusRequest`.  There are a couple options:
  - add a new `velero status` command that creates/displays all of the fields from a `ServerStatusRequest` (version, plugins, whatever else we want to add later)
  - have `velero plugin list` create a `ServerStatusRequest` and only display the list of plugins, ignoring other fields
  - not use `ServerStatusRequest` for listing plugins - have some other CRD that does it

What do you think makes sense here?

**Comment by carlisia** [comment]
I'm a fan of having a `velero status`. I'm sure we can find useful things to list for that command. 

But I would argue that having a `velero plugin list` is the most expected way to list plugins, so I'd rather go with that.

Because listing plugins doesn't seem to fit in a status request, it would make sense to me to use a separate CRD. But I'm not against reusing the existing `ServerStatusRequest`, especially if there's concern with cluttering the server with too many CRDs (is this a thing)? If not, I'd go with new CRD for plugin related things.

**Comment by skriss** [comment]
I mostly agree with your thoughts.  There is definitely development overhead with adding a new CRD/controller for every new thing, and I would argue that `ServerStatusRequest` is a fine place to put info about what plugins are currently loaded into the server.  So here's what I'd do:

- enhance `ServerStatusRequest` and its controller to list the plugins loaded into the server
- add `velero plugin list`, which will create an SSR, wait for it to be processed, and then display the list of plugins
- down the road, consider adding a `velero status` which can output all of the different fields on `ServerStatusRequest`.  I don't think it's needed right now since it'll just cover version and plugins, but can definitely see it being useful as we add more things to the CRD

**Comment by carlisia** [comment]
Perfect. Completely agree. 👍

**Comment by skriss** [comment]
Closed by #1535
