### ISSUE TITLE
Restic repository pruning

### ISSUE THREAD

**Issue by carlisia** [heptio/velero#1541]
Decide how to handle repository pruning (a maintenance operation that removes unused data blocks from the repository, which requires an exclusive repository lock and can be very slow for large repositories)

**Comment by skriss** [comment]
Currently, we run `restic prune` ("repository maintenance") every 24h by default for each repository.  It's not intelligently scheduled, i.e. we don't try to fit it in between scheduled backups.  A number of options here:

- run it less frequently
- don't run it at all by default; give the user some way to manually schedule/run it as needed
- wait for the fix for https://github.com/restic/restic/issues/2162 which should make `restic prune` faster
- try to intelligently schedule it between scheduled backups
- some combination of the above

**Comment by skriss** [comment]
Related to this - currently when we run "repo maintenance" we run `restic check`, then `restic prune`, then `restic check`. All of these require exclusive locks.  However, according to https://forum.restic.net/t/should-i-run-restic-check/1227, the `restic check` runs are probably not necessary since the `restic prune` operation is effectively a superset of `restic check`.

If this is the case, then we can remove the two `restic check` calls and save a bunch of time where the repo is exclusively locked.

**Comment by skriss** [comment]
I'm thinking that for now we should just run this less frequently by default (I'm thinking every 7d), and we wait for the upstream PR that makes `restic prune` much faster to get merged. I don't want to over-engineer this if this is going to become less of an issue going fwd. I've already made the change to remove the extraneous `restic check` operations as well, which will help too.

Does this sound reasonable? cc @nrb @prydonius @carlisia

**Comment by prydonius** [comment]
SGTM, perhaps we can make this configurable on `velero install`?

**Comment by nrb** [comment]
Sounds reasonable to me!

**Comment by skriss** [comment]
@prydonius we can definitely do that. Right now it's hardcoded to default to `24h`, and then that value is stored in each `ResticRepository` CR's `spec.maintenanceFrequency`, so technically a user could change the internal today by editing the YAML. If we made the default internal configurable via `velero install`, we'd probably need to add a `velero server` flag as well like `--default-restic-repo-maintenance-frequency`. It would still be editable by a user after-the-fact.
