### ISSUE TITLE
Backup item actions with only a namespace selector run for cluster-scoped resources

### ISSUE THREAD

**Issue by skriss** [heptio/velero#1552]
If you have a backup item action that's configured to run for 1+ specific namespaces, and it doesn't have a set of included resource types (i.e. it runs for **all** resource types), then it will **also** run for all cluster-scoped resources. This is not desired behavior -- if a specific set of namespaces are specified, it should only run for those namespaces.  This line is relevant:

https://github.com/heptio/velero/blob/master/pkg/backup/item_backupper.go#L297

**Comment by skriss** [comment]
Here's the unit test case that demonstrates the current bug: https://github.com/heptio/velero/blob/master/pkg/backup/backup_new_test.go#L690.

**Comment by prydonius** [comment]
I believe the issue is that around here (https://github.com/heptio/velero/blob/f3850210aacd6a3dc5eb4281ee28949cde4c1f14/pkg/backup/item_backupper.go#L297) we don't check if the resource is ClusterScoped and if `backupRequest.Spec.IncludeClusterResources` is false like we are doing here (https://github.com/heptio/velero/blob/f3850210aacd6a3dc5eb4281ee28949cde4c1f14/pkg/backup/item_backupper.go#L137)

Does that sound about right @carlisia @nrb? Also, should custom actions run for Namespace resources, given they are backed up even when IncludeClusterResources is false?

**Comment by carlisia** [comment]
This is actually the relevant test: https://github.com/heptio/velero/blob/f3850210aacd6a3dc5eb4281ee28949cde4c1f14/pkg/backup/backup_new_test.go#L739

The action, instead of:
`new(recordResourcesAction).ForNamespace("ns-1"): {"ns-1/pod-1", "ns-1/pvc-1", "pv-1", "pv-2"}`

...should be:
`new(recordResourcesAction).ForNamespace("ns-1"): {"ns-1/pod-1", "ns-1/pvc-1"}`

**Comment by carlisia** [comment]
I think you are right. But double check with the test.

**Comment by nrb** [comment]
@prydonius I believe you are correct.

> Also, should custom actions run for Namespace resources, given they are backed up even when IncludeClusterResources is false?

This is a little trickier. I think if the namespace is being included, then the custom actions should run, but if they are not (or explicitly excluded), then the custom actions shouldn't run.

So if my backup includes _only_ namespace A, the custom actions should run for namespace A and not other namespaces.

If my backup includes namespace A and cluster resources, the custom actions should run for all namespaces.

That's where I would start. Curious if anyone has any different thoughts on how it should behave.

**Comment by carlisia** [comment]
This makes sense to me @nrb.

**Comment by prydonius** [comment]
> So if my backup includes only namespace A, the custom actions should run for namespace A and not other namespaces.

Hmm, if I understand correctly the current behaviour matches this, in that if the backup request does not include the namespace, the item is skipped and so it never reaches https://github.com/heptio/velero/blob/f3850210aacd6a3dc5eb4281ee28949cde4c1f14/pkg/backup/item_backupper.go#L193 to trigger the custom action.

My question was actually more specifically about the Namespace kind resources, which according to https://github.com/heptio/velero/blob/f3850210aacd6a3dc5eb4281ee28949cde4c1f14/pkg/backup/item_backupper.go#L135-L137 we will always backup whether or not IncludeClusterResources is true. So does this mean that the custom actions should also be run for those Namespace resources that are backed up?

I might be missing something here though, so let me know if I'm not following this correctly!

**Comment by prydonius** [comment]
I'm a little confused about the behaviour of IncludeClusterResources. When backing up everything without any filters, it looks like cluster-scoped resources are backed up, but when restricted to a namespace only PVs cluster-resources are backed up (guessing this is due to the action on the Pod).

When IncludeClusterResources is nil (as it is in the test considered here), it will never be skipped in this condition (https://github.com/heptio/velero/blob/f3850210aacd6a3dc5eb4281ee28949cde4c1f14/pkg/backup/item_backupper.go#L135-L137) due to the `ib.backupRequest.Spec.IncludeClusterResources != nil` check - so it's as if IncludeClusterResources is true and the item should get backed up. Is that as expected?

**Comment by skriss** [comment]
> ) we don't check if the resource is ClusterScoped and if backupRequest.Spec.IncludeClusterResources is false like we are doing here...

Close - I think we should be checking if (a) the resource is cluster-scoped and (b) if the action's namespaces filters "include everything" similar to what's happening here: https://github.com/heptio/velero/blob/f3850210aacd6a3dc5eb4281ee28949cde4c1f14/pkg/backup/resource_backupper.go#L122

> Also, should custom actions run for Namespace resources, given they are backed up even when IncludeClusterResources is false?

Probably, yeah.

> I'm a little confused about the behaviour of IncludeClusterResources. When backing up everything without any filters, it looks like cluster-scoped resources are backed up, but when restricted to a namespace only PVs cluster-resources are backed up (guessing this is due to the action on the Pod).

Yeah, this is kind of confusing. We're trying to intelligently infer whether or not the user wants the cluster-scoped resources based on whether they're backing up **everything**, or only specific namespaces. It works as follows:
- If the user doesn't specify any specific included/excluded namespaces, then presumably they want a full-cluster backup. In this case, **all** cluster-scoped resources should be backed up. If `--include-cluster-resources` is nil (which is the default), they'll get this behavior.
- As a modification to the previous case, if the user *only* wants namespaced resources, they can specify `--include-cluster-resources=false`.
- If the user specifies 1+ specific included namespaces (i.e. `--include-namespaces=ns-1,ns-2`), then presumably they only want the resources in those namespaces and any PVs used by those namespaces, not **all** cluster-scoped resources. If `--include-cluster-resources` is nil (which is the default), they'll get this behavior.
- as a modification to the previous case, if the user *does* in fact want all cluster-scoped resources in addition to the resources in ns-1/ns-2, they can specify `--include-cluster-resources=true`.

Separately, if we're backing up any of the resources within a namespace, we also back up the Namespace resource itself, which I think you also alluded to somewhere.

**Comment by skriss** [comment]
Closed by #1601.
