### ISSUE TITLE
Validate for hostPath mount for restic

### ISSUE THREAD

**Issue by carlisia** [heptio/velero#1557]
As can be seen here: https://github.com/heptio/velero/blob/4e2e4cd5c434791ab865abcb858e2a6c053355ad/site/docs/master/restic.md#instructions, there a hostPath will be different depending on the backend.

In addition to documenting it, we should add a validation check and return an error when the hostPath is misconfigured.

**Comment by nrb** [comment]
What are we defining as "misconfigured"? That the configured hostPath isn't found? Keeping up with all k8s distributions defined hostPath would probably be difficult, so I'm not sure we want to hard code checks for that.

**Comment by skriss** [comment]
My thinking on this is that there's a defined directory structure that we'd expect to see if the hostPath mount is properly pointing to the `/var/lib/kubelet/pods` directory equivalent for the relevant distro, along the lines of:

```
- <pod-1-uid>/
  - containers/
  - plugins/
  - volumes/
  - ...
- <pod-2-uid>/
- ...
```

So we could come up with some sort of validation that what we see in the mount matches what a `/var/lib/kubelet/pods` directory *should* look like.

**Comment by skriss** [comment]
We could just look up which pods are running on the node, and then ensure that we see all their UIDs as directories under the hostPath mount. That should be pretty foolproof.

**Comment by nrb** [comment]
I like the UID option better, since looking at the structure is really trying to look at an implementation detail of Kubernetes, which might change, whereas the UID approach is less coupled to the k8s design.

Admittedly, kubernetes isn't likely to change that without some decent lead time, but still, I'd like this kind of check to be as stable as possible.

**Comment by prydonius** [comment]
One thing I've noticed is that mirror pods running on the node use the value of their `kubernetes.io/config.hash`/`config.mirror` annotation rather than `metadata.uid` for the directory name under `/var/lib/kubelet/pods`. Other than that, the directory structure beneath it is the same. We'll need to check if that annotation is there and use that instead of the UID if it is when looking up pods.
