### ISSUE TITLE
Restic Backup - HowTo

### ISSUE THREAD

**Issue by Berndinox** [heptio/velero#1622]
So far the Documentation regarding Restic is clear
For Reference: https://velero.io/docs/v1.0.0/restic/

But i miss some Feature/Information.

Let's start with what i have done already:

I've added the annotation for the pods in the deployment:
```
spec:
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: volume-name-to-backup

```
I triggered an backup:
`velero backup create berndklaus-at --include-namespaces berndklaus-at`

When performing:
`velero restic repo get`
I can see a repo was added, there was no repo before performing the velero backup command.

`velero backup get`
I can see a backup, state: completed

OK, thats fine.
Well now i wont to take a newew backup of the above things, so i fired:
`velero backup create berndklaus-at --include-namespaces berndklaus-at`
That does not work, cause the backup still exists.

Ok, i delete the backup "berndklaus-at"
But when looking into my spaces, i can still see the restic part is NOT removed.
So i tought, there should be a command like: "velero restic backup delete." But i did not find a way to remove a restic backup.

So there came up a few questions:

What does the restic repo represent? 
How can i manage restic backups (delete/recreate/...)?
How can i trigger a restic backup only?
Does a schedule also starts a restic backup?

Please excuse typos and/or bad english.
Thanks for clearification, BR Bernd

**Comment by skriss** [comment]
@Berndinox good questions! 

> What does the restic repo represent?

Restic uses "repositories" to organize backup data. Velero creates one per namespace + backup storage location.

> How can i manage restic backups (delete/recreate/...)?

In velero, restic backups are always tied to a main "velero backup". When you delete a velero backup, we run the `restic forget` command which deletes metadata about the restic backup from the repository. Separately, there's a  recurring `restic prune` operation that runs for each repository every 24h by default, that deletes the actual blocks of data. We do this asynchronously because it can be slow.

> How can i trigger a restic backup only?

Velero does not support this - all restic backups are tied to a main "velero backup".

> Does a schedule also starts a restic backup?

Yes, if you have workload pods annotated!

**Comment by Berndinox** [comment]
Ok, thanks alot for clearification!

**Comment by skriss** [comment]
Closing this issue out.
