### ISSUE TITLE
Whether restic backups guarantee data integrity for running pods?

### ISSUE THREAD

**Issue by cntsw** [heptio/velero#1738]
I want to use Velero Restic to backup database(Postgres) Deployment, which uses a Rook-Ceph rbd volume. I don't want the volume to be backup while the pod is running, because I'm worried about breaking data integrity. 

Is it necessary a mechanism like [Offline Backup](https://appscode.com/products/stash/0.8.3/guides/offline_backup/) to back up when the pod is stopped?

kubernetes verson: `v1.13.2`
velero version: `v1.0.0`

**Comment by skriss** [comment]
@cntsw by default, you won't get any consistency guarantees with restic backups. However, you can use [hooks](https://velero.io/docs/v1.0.0/hooks/) to run arbitrary commands in your pod before/after taking a backup to quiesce your application or do anything else you need to. Our [nginx example manifest](https://github.com/heptio/velero/blob/master/examples/nginx-app/with-pv.yaml#L55) demonstrates using hooks to use `fsfreeze` to pause writes during the backup.

Hope that helps.

**Comment by skriss** [comment]
Closing out, feel free to reopen as needed!

**Comment by alexfouche** [comment]
_just a comment, no need to reopen_

In practice nothing works, because : 

1. on recent versions, Postgres has no more way to quiesce using Velero hooks, because  Postgres session must be kept open between `pg_backup_start(...)` and `pg_backup_stop()`
2. because in most cases, DB containers are not run as `root`, and so Velero hooks have no permissions to execute `fsfreeze`
