### ISSUE TITLE
Restoration with label selector does not properly restore PVs

### ISSUE THREAD

**Issue by jrnt30** [heptio/velero#314]
I recently took a full backup of our cluster `ark create backup complete`.  This backup includes several components and I wanted to test the restoration of just a subset of these initially.  

In an alternate cluster which was setup with to leverage the same S3 bucket for backup state I ran `ark create restore complete -l release=jenkins` as an attempt to only restore the relevant Jenkins resources.  

The restoration shows that it was successful and in the logs it does show that the PVC itself is being restored, however that PVC remains in a `Lost` state.  It seems that the logic to restore the underlying `PV` is filtering out the resource. 

NOTE: I also attempted to create a more granular backup, using the same selector `ark create backup jenkins -l release=jenkins`.  Restoring that application specific backup without an explicit label selector *does* work properly.  So it seems to be the combination of the `--selector` in the `restore` command that negatively impacts the resulting restore. 

Talking with Andy, he mentioned that the logic now does some additional `Pod -> PVC -> PV` logic that may need to be incorporated into the restoration process as well.  

Ark version: 
```
ark version
Version: v0.6.0
Git commit: v0.6.0
Git tree state: clean
```

K8 Version: 
```kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T19:59:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by nrb** [comment]
I verified that modifying the conditional at  https://github.com/heptio/ark/blob/master/pkg/restore/restore.go#L553 to be 

`if !ctx.selector.Matches(labels.Set(obj.GetLabels())) && obj.GetNamespace() != "" ` 

will restore the namespace, but I'm not really happy with that as a solution. It works because we're already processing a list of all the files, but by doing this we restore *any* cluster scoped resource.

If we mirror the `additionalActions` approach from the backup/pod_action.go file, I think we can change the signature of the restore PodAction to provide an additional `runtime.Unstructured` representing the PV, or simply return a list of names to be looked up. 

We may have to extract some of the restore logic so that a "subrestore" can happen, similar to how we use an [extra ItemBackupper](https://github.com/heptio/ark/blob/master/pkg/backup/item_backupper.go#L214).

Does this sound reasonable @ncdc and @skriss, or am I misunderstanding some aspect of the process?

**Comment by ncdc** [comment]
@nrb `if !ctx.selector.Matches(labels.Set(obj.GetLabels())) && obj.GetNamespace() != ""` is not an appropriate fix. We need to implement the pod -> pvc -> pv logic for restores, and this change doesn't do that.

> If we mirror the additionalActions approach from the backup/pod_action.go file, I think we can change the signature of the restore PodAction to provide an additional runtime.Unstructured representing the PV

We can't really do this, as the function `Execute(obj runtime.Unstructured, restore *api.Restore) (runtime.Unstructured, error, error)` is part of the `restore.ItemAction` interface.

> or simply return a list of names to be looked up.

This would match what we do for `backup.ItemAction`.

> We may have to extract some of the restore logic so that a "subrestore" can happen, similar to how we use an extra ItemBackupper.

This is in line with my thinking.

**Comment by nrb** [comment]
I think I have a rough proposal for addressing this.

Prerequisite changes
Make `restore.ItemAction.Execute` return additional items to restore.
Modify `runRestore` to check for the label selector as well as whether or not the item is an additional item

In `runRestore`: 
 1. enqueue the additional items returned by `restore.ItemAction.Execute` in a `ctx.additionalItems` set field
 1. For each additional item, get resource and filepath out of the backup
 1. Call runRestore on each additional item to restore
 1. Remove item from `ctx.additionalItems` field once restored

**Comment by ncdc** [comment]
@nrb did you consider following the backup pattern, where we process the additional items immediately, instead of storing them in `ctx`? We'd probably need to split `restoreResource` apart a bit, since it currently combines looping through e.g. all pods and restoring them, instead of using 1 function to loop and a second to restore per item.

**Comment by nrb** [comment]
@ncdc That's actually the intent; I updated the comment because I had the `restore_controller.runRestore` function and `restore.restoreResource` functions mixed up in my notes.

The logic behind the list is that https://github.com/heptio/ark/blob/master/pkg/restore/restore.go#L630 only looks at the selector, and we need some other condition to go along with that. I wasn't coming up with much better. I'd process them immediately, and use the list to denote a special case that doesn't match the selector. Certainly open to other ideas here though.

I think breaking the current `restoreResource` apart would also be needed for the reasons you mention.

**Comment by ncdc** [comment]
WIP in #1125. Targeting v0.12
