### ISSUE TITLE
Add support for restoring container images as well (!?)

### ISSUE THREAD

**Issue by containscafeine** [heptio/velero#464]
Let's say a backup is created today, and restored a year later. And the container images that are referenced in the backup no longer exist. Also, the images might have been altered over time and the restore might not behave the same way as the application did at the time of backup.
Does it make sense to support an optional backing up of container images as well?
This could also be hinting at doing something like static backups with no external dependencies.
Thoughts?

**Comment by ncdc** [comment]
@containscafeine definitely an interesting idea. If we wanted to do something like this, Ark would need to be able to access all the images in the cluster. Given that some very well may have been pulled using image pull secrets, Ark would either need to use those same pull secrets, or we'd need to run a separate DaemonSet on all nodes. For a given (pod, image) on a node, if Ark hasn't backed it up before, we'd have to ask the Ark DaemonSet pod running on that node to back up the image (it would need access to the docker socket).

If we decide to do this, I think it'll be a p3 / long term goal.

cc @jbeda

**Comment by rosskukulinski** [comment]
This is certainly an interesting request, but not one that I think many users would be interested in [happy to be told otherwise].

If I understand the request correctly, the idea is what happens if when you go to restore a backup, the container images that are referenced are no longer available (or have been altered - e.g. :master or :latest).

In my opinion, the second part - they’ve been altered, goes against one of the key items to being successful with containers: immutability.  Image tags (besides master and latest) should never change - and you shouldn’t use master or latest outside development.

As for container images no longer being available -- this sounds like you have much worse problems -- your container registry is entirely gone?  What does doing a restore buy you anything?  Even if your registry is hosted within the cluster that you’re trying to restore… at a minimum that registry container should not reference itself.  

I typically recommend having a `bootstrap` cluster that includes the core systems that you need (logging, monitoring, registry, auth) and none of those components should depend on internal systems.  All container images are stored elsewhere, data not stored on local systems.

So with those things in mind, I don't think this particular feature is a high priority item.  But I'm happy to collect more use-cases that I haven't considered yet.

**Comment by containscafeine** [comment]
I agree with the best practices and having processes in place to deal with such problems, that you've listed, but my use-case was having this problem as a service provider with no control on how the end users use your services.
Let's say, the online service that you provide to your customers, takes in the container image from the end user, and deploys it to your cluster with 100 other awesome features. And the user does not return for 6 months, and having the user's service up and running for 6 months will cost a lot of money. So, after a month, we see that the user is gone, and we perform an automated backup.
This will happen for hundreds of thousands of users, and we cannot set up best practices and processes in this case.
Hence, this issue/feature request.
Maybe @kbsingh can elaborate more on this.

**Comment by skriss** [comment]
Thanks for this request. We are not currently prioritizing this item within our roadmap, and as such will be closing out the issue. Please feel free to reach out as needed in this issue or a new one.
