### ISSUE TITLE
Allow admin to tweak restic restore helper image

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#638]
**User Story**

As a user of Ark with Restic, I would like to customize the restic container image that is deployed as an initContainer to Pods during a restore.

---

https://github.com/heptio/ark/blob/32907931e13f38ef4e055652245eeb78d20ac76e/pkg/restore/restic_restore_action.go#L53

Make it a flag to `ark server`?

**Comment by rosskukulinski** [comment]
As this isn't a breaking change, I don't think it must land in v1.0.0.  Community contributions welcome if someone wants to accelerate the development of this feature.

**Comment by ljfranklin** [comment]
@ncdc @rosskukulinski I'd be willing to try a PR to add this flag. I'm trying to use Ark on a Raspberry Pi, the backup is working fine but the restore stumbles due to the restic helper image not supporting ARM. That said, I'm having trouble figuring out how to pass the image name from [server.go](https://github.com/heptio/ark/blob/2781e4e8de08bb33585eb945819ad989bf972b49/pkg/cmd/server/server.go#L166) down to [restic_restore_action.go](https://github.com/heptio/ark/blob/2781e4e8de08bb33585eb945819ad989bf972b49/pkg/restore/restic_restore_action.go#L53). It looks like this restic restore object is initialized in a separate [`run-plugins` command](https://github.com/heptio/ark/blob/2781e4e8de08bb33585eb945819ad989bf972b49/pkg/cmd/server/plugin/plugin.go#L55) and it seems awkward to pass the restic image name as a command line arg to `run-plugins`. Is there some config object that would make sense to hold a `resticRestoreHelperImage` property?

**Comment by patrickstjohn** [comment]
+1 on this. This issue prevents restoration of restic backups on any internet segregated cluster.

**Comment by encryptedfear** [comment]
Hi,

If I made canges to the `ark/pkg/restore/resti_restore_action.go`, will it take effect on my next backup? Or is there another step that I've to do? I can't pull the image from gcr.io/heptio-images/ark-restic-restore-helper:v0.10.0 due to internet restrictions in our cluster.

**Comment by ncdc** [comment]
@encryptedfear did you build a new ark image with your changes?

Another short-term option would be to pre-pull our image into your environment, then pre-load it onto all your nodes. I think that might work - unless the `ImagePullPolicy` (which we aren't setting) gets set to `Always`.

**Comment by encryptedfear** [comment]
Hi,

Sorry for the delay in response. No I haven't built one yet. Haven't been back to the office yet.
I'll try that approach, thanks.

**Comment by encryptedfear** [comment]
Hi @ncdc

As of the moment, there are far too many restrictions for me to build the image, as there are items to be white-listed on our side when I try to `make update` and `make build` alone. Is there any other way of changing the URL of the restic-restore-helper? In this case, the internet access is a void, unfortunately. We can only pull from a private Docker repository, and that's all the connection we can get on our side.

May I ask, is there a source file inside the image (of ark) that I can tweak via `kubectl exec -it ark-container -- sh` to change the URL only?

Cheers

**Comment by ncdc** [comment]
@encryptedfear this requires a code change. We'll see if we can get a fix out for you soon.

**Comment by skriss** [comment]
xref #584
